<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <?php $this->partial('nav'); ?>

  <main role="main" class="inner cover">
	<h1 class="cover-heading text-center">注意</h1>
	<h5 class="text-center">記録をとるために、お先にログインしてください。</h5>
	  	<p class="text-center">
	 		<?=$this->tag->linkTo('user/login','≫ログインはこちら'); ?>
	  	</p>
	</form>
  </main>

  <footer class="mastfoot mt-auto">
	<div class="inner">
	  <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
	</div>
  </footer>
</div>