<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <?php $this->partial('nav'); ?>

  <main role="main" class="inner cover">
	<h1 class="cover-heading text-center">Attention</h1>
	<h5 class="text-center">In order to save your records, please login.</h5>
	  	<p class="text-center">
	 		<?=$this->tag->linkTo('user/login','≫Login Here'); ?>
	  	</p>
	</form>
  </main>

  <?php $this->partial('footer'); ?>
</div>