<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <?php $this->partial('nav'); ?>

  <main role="main" class="inner cover">
	<h1 class="cover-heading text-center">注意</h1>
	<h5 class="text-center">記録をとるために、お先にログインしてください。</h5>
	  	<p class="text-center">
	 		<?=$this->tag->linkTo('user/login','≫ログインはこちら'); ?>
	  	</p>
	</form>
  </main>

  <?php $this->partial('footer'); ?>
</div>