<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <?php $this->partial('nav'); ?>

  <main role="main" class="inner cover">
	<h1 class="cover-heading">ログイン</h1>
	<br />
	<?php echo $this->tag->form("user/login"); ?>
		<div class="input-group mb-3">
		  <div class="input-group-prepend">
			<span class="input-group-text" id="inputGroup-sizing-default">E-mail</span>
		  </div>
		  <?php echo $this->tag->emailField(array("name"=>"email","id"=>"email","class"=>"form-control","value"=>$this->request->getPost('email'))); ?>
		</div>
	    <div class="input-group mb-3">
		  <div class="input-group-prepend">
			<span class="input-group-text" id="inputGroup-sizing-default">Password</span>
		  </div>
		  <?php echo $this->tag->passwordField(array("type"=>"password","name"=>"password","id"=>"password","class"=>"form-control","value"=>$this->request->getPost('password'))); ?>
		</div>
	    <br />
	  	<p class="text-center">
			<?php echo $this->tag->submitButton(array("class"=>"btn btn-primary","value"=>"ログイン")); ?>
		</p>
	 <?php if($is_error): ?>
	  	<div>Error:</div>
	  	<?=$this->flashSession->output() ?>
	 <?php endif; ?>
	  	<p class="text-center">
	 		<?=$this->tag->linkTo('user/register','≫登録はこちら'); ?>
	  	</p>
	</form>
  </main>

  <footer class="mastfoot mt-auto">
	<div class="inner">
	  <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
	</div>
  </footer>
</div>