<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <?php $this->partial('nav'); ?>

  <main role="main" class="inner cover">
	<h1 class="cover-heading">Signup</h1>
	<br />
	<?php echo $this->tag->form(array("action"=>"/user/register","id"=>"form")); ?>
		<div class="input-group mb-3">
		  <div class="input-group-prepend">
			<span class="input-group-text" id="inputGroup-sizing-default">E-mail</span>
		  </div>
		  <?php echo $this->tag->textField(array("name"=>"email","id"=>"email","class"=>"form-control","value"=>$this->request->getPost('email'),"required"=>"required")); ?>
		</div>
	    <div class="input-group mb-3">
		  <div class="input-group-prepend">
			<span class="input-group-text" id="inputGroup-sizing-default">Password</span>
		  </div>
		  <?php echo $this->tag->passwordField(array("type"=>"password","name"=>"password","id"=>"password","class"=>"form-control","value"=>$this->request->getPost('password'),"required"=>"required")); ?>
		</div>
	  	<div class="input-group mb-3">
		  <div class="input-group-prepend">
			<span class="input-group-text" id="inputGroup-sizing-default">Again</span>
		  </div>
		  <?php echo $this->tag->passwordField(array("name"=>"confirmPassword","id"=>"confirmPassword","class"=>"form-control","value"=>$this->request->getPost('confirmPassword'),"required"=>"required")); ?>
		</div>
	  	<input type="text" name="terms" class="hidden" value="yes" />
	  	<input type="text" name="name" class="hidden" value="aaa" />
	  	<input type="submit" class="hidden" />
	</form>
	    <br />
	  	<p class="text-center">
			<button id="submit" class="btn btn-primary" >Login</button>
		</p>
	 	<div class="block_error" style="display: none;">
			<div>Error:</div>
			<div class="content"></div>
	 	</div>
	  	<p class="text-center">
	 		<?=$this->tag->linkTo('user/login','≫Login Here'); ?>
	  	</p>
	  	<?php echo $this->tag->textField(array("name"=>"name","id"=>"name","class"=>"hidden","value"=>'aaa')); ?>
	    <input type="checkbox" class="hidden" name="terms" value="yes" checked />
  </main>

  <?php $this->partial('footer'); ?>
</div>
<div class="text_msg hidden"><div class="msg"></div></div>