<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <?php $this->partial('nav'); ?>

  <main role="main" class="inner cover">
	<h1 class="cover-heading">Leader Board</h1>
	<table class="table table-striped">
    <thead>
    <tr>
        <th class="rank">Rank</th>
        <th class="name">Name</th>
        <th class="score">Score</th>
        <th class="level">Level</th>
		<th class="last">Last Play</th>
    </tr>
    </thead>
    <tbody>
	<?php foreach($rank as $i=>$row): ?>
    <tr>
        <td class="rank"><?=$i+1 ?></td>
        <td class="name"><?=$row["name"] ?></td>
        <td class="score"><?=number_format($row["score"]) ?></td>
        <td class="level"><?=number_format($row["level"]) ?></td>
		<td class="last"><?=$row["last_datetime"] ?></td>
    </tr>
	<?php endforeach; ?>
    
    </tbody>
	</table>
	
  </main>

  <footer class="mastfoot mt-auto">
	<div class="inner">
	  <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
	</div>
  </footer>
</div>