<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.1&appId=1418954798320001&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <?php $this->partial('nav'); ?>

  <main role="main" class="inner cover">
	<h1 class="cover-heading">Leader Board
		<div class="fb-share-button" data-href="http://54.168.66.247/rank" data-layout="button" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F54.168.66.247%2Frank&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">分享</a></div>
	</h1>
	<div class="block_no_user" style="display: none;">
		<br>
		<p>There is no user yet.</p>
	</div>
	<div class="block_rank"  style="display: none;">
		<div class="table-responsive">
			<table class="table">
			<thead>
			<tr>
				<th class="rank">Rank</th>
				<th class="name">Name</th>
				<th class="score">Score</th>
				<th class="level">Level</th>
				<th class="last">Last Play</th>
			</tr>
			</thead>
			<tbody class="block_tr">

			</tbody>
			</table>
		</div>
	</div>
  </main>

  <?php $this->partial('footer'); ?>
</div>
<div class="text_tr hidden">
	<table>
		<tr> 
			<td class="rank"><span></span></td>
			<td class="name"><span></span></td>
			<td class="score"><span></span></td>
			<td class="level"><span></span></td>
			<td class="last"><span></span></td>
		</tr>
	</table>
</div>
<div class="text_follow hidden">
	<?php echo $this->tag->form("user/follow"); ?>
		<input type="text" name="target_id" class="hidden" value="" />
	</form>
</div>
<div class="text_follow_btn hidden">
	<button type="button" class="btn btn-primary btn-sm btn-follow">Follow</button>
</div>
<div class="text_unfollow hidden">
	<?php echo $this->tag->form("user/unfollow"); ?>
		<input type="text" name="target_id" class="hidden" value="" />
	</form>
</div>
<div class="text_unfollow_btn hidden">
	<button type="button" class="btn btn-success btn-sm btn-follow">UnFollow</button>
</div>