<!DOCTYPE html>
<html>
    <head>
		<meta property="og:image" content="http://http://54.168.66.247/public/img/pac_man_hed.jpg" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Pacman</title>
		<?php $this->assets->outputCss(); ?>
		<?php $this->assets->outputJs(); ?>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
    </body>
</html>
