<header class="masthead mb-auto">
	<div class="inner">
	  <h3 class="masthead-brand">Pacman</h3>
	  <nav class="nav nav-masthead justify-content-center">
		<a class="nav-link<?=$nav=='play'?' active':'' ?>" href="/play">Play</a>
		<a class="nav-link<?=$nav=='rank'?' active':'' ?>" href="/rank">Ranking</a>
	  <?php if(false === $this->auth->isUserSignedIn()): ?>
		<a class="nav-link<?=$nav=='user'?' active':'' ?>" href="/user/login">Login</a>
		
	  <?php else: ?>
		<a class="nav-link<?=$nav=='user'?' active':'' ?>" href="/user/signout">Logout</a>
		<div class="nav-user text-info">Hello, <a class="text-info" href="#"><?=$this->session->get('')["name"] ?></a></div>
	  <?php endif; ?>
	  </nav>
	</div>
</header>